server:
  # 默认端口
  port: 8081
  tomcat:
  # post提交允许8M(8192)
    max-http-post-size: 10240
  # 解决Error parsing HTTP request header?
    max-http-header-size: 8192
    
spring: 
  # 数据库
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/server_ports?characterEncoding=utf-8&useSSL=false&useAffectedRows=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    # hikari配置(官网：https://github.com/brettwooldridge/HikariCP)
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      # 连接池名字
      pool-name: serverPorts-HikariCP
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 数据库连接超时时间,默认30秒，即30000，当前30秒
      connection-timeout: 30000
#      connection-test-query: select 1
      # 空闲连接存活最大时间，默认600000（10分钟）空闲(idle)活动(active)，当前30秒
      idle-timeout: 30000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟，
      # - 比数据库wait_timeout/超时时长参数少30秒即可（show variables like ‘%timeout%’），当前7小时
      max-lifetime: 25200000
      # minimum-idle：最小空闲连接数量（不设置则默认等于maximum-pool-size）
      # 连接池最大连接数，默认是10，(core_count * 2) + effective_spindle_count，设置太大影响性能
      maximum-pool-size: 10

# 数据库操作
mybatis: 
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: cn.mrjingchen.ServerInfo.model

